name: RAG
on:
  push:
    paths-ignore:
      - "**/*.lock"
      - "**/*.toml"
      - "**/README.md"

  pull_request:
    paths-ignore:
      - "**/*.lock"
      - "**/*.toml"
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: make install

      - name: Lint code with ruff
        run: make lint

      - name: Format code with ruff
        run: make format

      - name: Test with pytest
        run: make test

      - name: Build Docker Container
        run: make build